# Generated by Django 5.2.5 on 2026-08-28 07:43

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('excerpt', models.CharField(max_length=400)),
                ('content', models.TextField()),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('category', models.CharField(blank=True, max_length=100)),
                ('author', models.CharField(default='Daaru Najat Team', max_length=100)),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=40, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Inquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('appointment', 'New Appointment'), ('inquiry', 'New Inquiry'), ('order', 'New Order'), ('subscriber', 'New Subscriber'), ('promotion', 'Promotion Alert'), ('general', 'General')], default='general', max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_phone', models.CharField(max_length=20)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('delivery_address', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('ready', 'Ready'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('short_description', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('ingredients', models.TextField(blank=True, help_text='One ingredient per line.')),
                ('benefits', models.TextField(blank=True, help_text='Key benefits/uses, one per line.')),
                ('how_to_use', models.TextField(blank=True, help_text='Recommended usage / preparation instructions.')),
                ('precautions', models.TextField(blank=True, help_text='Warnings, contraindications, safety notes.')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('track_stock', models.BooleanField(default=True, help_text='If off, product is always shown as available.')),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True, help_text='Visible on the public site.')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon_name', models.CharField(default='Leaf', help_text='Lucide icon name e.g. Leaf, Flower2, Sprout', max_length=50)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Product Categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('short_description', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('icon_name', models.CharField(default='Leaf', help_text='Lucide icon name e.g. Leaf, Heart, Star', max_length=50)),
                ('category', models.CharField(choices=[('herbal_medicine', 'Herbal Medicine'), ('spiritual_healing', 'Spiritual Healing'), ('cupping', 'Cupping Therapy'), ('massage_therapy', 'Massage Therapy'), ('dietary_healing', 'Dietary Healing'), ('other', 'Other')], default='other', max_length=30)),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_featured', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Daaru Najat', max_length=100)),
                ('tagline', models.CharField(default='...healing hands, divine touch!', max_length=200)),
                ('logo', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='logo')),
                ('favicon', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='favicon')),
                ('primary_color', models.CharField(default='#3A7D44', max_length=7)),
                ('secondary_color', models.CharField(default='#C49A3C', max_length=7)),
                ('accent_color', models.CharField(default='#B0683A', max_length=7)),
                ('contact_email', models.EmailField(default='abiodunnajaat@gmail.com', max_length=254)),
                ('contact_phone', models.CharField(default='08029001826', max_length=20)),
                ('contact_phone2', models.CharField(blank=True, max_length=20)),
                ('whatsapp_number', models.CharField(default='2348062952711', help_text='Digits only e.g. 2348062952711', max_length=20)),
                ('whatsapp_greeting', models.TextField(default='Salaam! I am interested in the healing services at Daaru Najat.')),
                ('address', models.TextField(default='11, Animasahun Close, Alaguntan, Iyana-ipaja, Lagos')),
                ('city', models.CharField(default='Lagos', max_length=100)),
                ('country', models.CharField(default='Nigeria', max_length=100)),
                ('hero_headline', models.CharField(default='Healing Rooted in Tradition', max_length=200)),
                ('hero_subheadline', models.TextField(default='Experience the sacred art of tradomedical healing.')),
                ('hero_cta_primary', models.CharField(default='Explore Our Services', max_length=100)),
                ('hero_cta_secondary', models.CharField(default='Book a Session', max_length=100)),
                ('hero_video_url', models.URLField(blank=True)),
                ('social_facebook', models.CharField(blank=True, default='Daaru Najat Tradomedicals', max_length=200)),
                ('social_instagram', models.CharField(blank=True, max_length=200)),
                ('social_tiktok', models.CharField(blank=True, max_length=200)),
                ('footer_description', models.TextField(default='Daaru Najat is a sacred traditional medical healing home.')),
                ('seo_title', models.CharField(default='Daaru Najat | Tradomedical Healing Home', max_length=200)),
                ('seo_description', models.TextField(default='Experience the sacred power of traditional healing in Lagos.')),
                ('seo_keywords', models.TextField(default='traditional healing, herbal medicine, Lagos')),
                ('about_title', models.CharField(default='About Daaru Najat', max_length=200)),
                ('about_description', models.TextField(default='A sacred tradomedical healing home serving Lagos and beyond.')),
                ('about_mission', models.TextField(default='To restore health and harmony through traditional medicine.')),
                ('about_vision', models.TextField(default='A world where ancient healing wisdom brings complete wellness.')),
                ('registration_no', models.CharField(blank=True, default='RC-2705184', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('content', models.TextField()),
                ('condition', models.CharField(blank=True, help_text='e.g. Fibroid Treatment, Diabetes', max_length=100)),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('is_approved', models.BooleanField(db_index=True, default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='api.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='api.productcategory'),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='api.product')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage Off'), ('fixed', 'Fixed Amount Off')], default='percentage', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Percentage (e.g. 20 for 20%) or a fixed NGN amount, depending on the type above.', max_digits=10)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True, help_text='Turn off to pause without deleting.')),
                ('is_featured', models.BooleanField(default=False, help_text='Featured promotions are shown first.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='api.product')),
            ],
            options={
                'ordering': ['-is_featured', 'start_date'],
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='api.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='api.product')),
            ],
            options={
                'unique_together': {('cart', 'product')},
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(blank=True, max_length=200)),
                ('appointment_date', models.DateField(blank=True, null=True)),
                ('preferred_time', models.CharField(blank=True, choices=[('08:00', '08:00'), ('08:30', '08:30'), ('09:00', '09:00'), ('09:30', '09:30'), ('10:00', '10:00'), ('10:30', '10:30'), ('11:00', '11:00'), ('11:30', '11:30'), ('12:00', '12:00'), ('12:30', '12:30'), ('13:00', '13:00'), ('13:30', '13:30'), ('14:00', '14:00'), ('14:30', '14:30'), ('15:00', '15:00'), ('15:30', '15:30'), ('16:00', '16:00'), ('16:30', '16:30'), ('17:00', '17:00'), ('17:30', '17:30'), ('18:00', '18:00'), ('18:30', '18:30')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], db_index=True, default='pending', max_length=20)),
                ('contact_name', models.CharField(max_length=200)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_appointments', to='accounts.patientprofile')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='api.service')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'confirmed')), fields=('appointment_date', 'preferred_time'), name='unique_confirmed_slot')],
            },
        ),
    ]
