# Generated by Django 5.2.5 on 2026-08-28 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='booking_notification_email',
            field=models.EmailField(blank=True, help_text='Where new-booking emails are sent. Falls back to Contact Email if left blank.', max_length=254),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='booking_whatsapp_number',
            field=models.CharField(blank=True, help_text='Digits only with country code, e.g. 2348012345678. Receives automatic WhatsApp Business booking alerts. Falls back to the WhatsApp Number above if left blank.', max_length=20),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email_notifications_enabled',
            field=models.BooleanField(default=True, help_text='Send an email to the address below whenever a new booking comes in.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='whatsapp_notifications_enabled',
            field=models.BooleanField(default=False, help_text='Send an automatic WhatsApp Business message whenever a new booking comes in. Requires WHATSAPP_BUSINESS_API_TOKEN and WHATSAPP_BUSINESS_PHONE_NUMBER_ID to be configured on the server -- turning this on without them configured will not silently fail; check Notifications in the dashboard or the server logs.'),
        ),
    ]
