# Generated by Django 5.2.5 on 2026-08-30 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_sitesettings_booking_notification_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='author',
            field=models.CharField(default='PHARA Team', max_length=100),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='about_description',
            field=models.TextField(default='A premium herbal wellness brand dedicated to natural healing, education, and quality botanical products.'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='about_mission',
            field=models.TextField(default='To make trusted, high-quality herbal wellness accessible to everyone.'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='about_title',
            field=models.CharField(default='About PHARA', max_length=200),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='about_vision',
            field=models.TextField(default='A world where natural wellness and modern living exist in harmony.'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_description',
            field=models.TextField(default='PHARA is a premium herbal wellness brand, blending traditional botanical knowledge with modern quality standards.'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_cta_primary',
            field=models.CharField(default='Shop Herbal Products', max_length=100),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_cta_secondary',
            field=models.CharField(default='Book a Consultation', max_length=100),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_headline',
            field=models.CharField(default='Timeless Wellness, Naturally Refined', max_length=200),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_subheadline',
            field=models.TextField(default='Premium herbal remedies crafted with ancient wisdom and modern care.'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='seo_description',
            field=models.TextField(default='Discover premium herbal products and wellness education from PHARA — traditional botanical wisdom, modern quality.'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='seo_keywords',
            field=models.TextField(default='herbal wellness, natural remedies, herbal products, wellness education, Lagos'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='seo_title',
            field=models.CharField(default='PHARA | Premium Herbal Wellness', max_length=200),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(default='PHARA', max_length=100),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='social_facebook',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='tagline',
            field=models.CharField(default="Nature's Wisdom, Refined", max_length=200),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='whatsapp_greeting',
            field=models.TextField(default='Hello PHARA! I would like to know more about your herbal wellness products.'),
        ),
    ]
