# Generated by Django 5.2.5 on 2026-09-12 03:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_blogpost_author_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='url',
            field=models.CharField(blank=True, help_text='Dashboard link to the related record, e.g. /dashboard/orders/12/', max_length=500),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='enquiry_email_notifications_enabled',
            field=models.BooleanField(default=True, help_text='Send an email whenever a new contact/product enquiry comes in.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='notification_email',
            field=models.EmailField(blank=True, help_text='Where new-inquiry and new-order alerts are sent. Falls back to Contact Email if left blank. Booking alerts use Booking Notification Email instead.', max_length=254),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='notification_sound',
            field=models.CharField(choices=[('chime', 'Chime'), ('gentle', 'Gentle'), ('none', 'Silent')], default='chime', help_text='Default notification sound for the staff dashboard.', max_length=20),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='notification_sound_enabled',
            field=models.BooleanField(default=True, help_text='Default sound preference for dashboard notifications. Users can override per device in the dashboard.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='notification_whatsapp_enabled',
            field=models.BooleanField(default=False, help_text='Send an automatic WhatsApp Business message for new enquiries and orders. Requires WHATSAPP_BUSINESS_API_TOKEN and WHATSAPP_BUSINESS_PHONE_NUMBER_ID.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='order_email_notifications_enabled',
            field=models.BooleanField(default=True, help_text='Send an email whenever a new product order comes in.'),
        ),
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(db_index=True, max_length=500, unique=True)),
                ('p256dh', models.CharField(help_text='Public key (base64url) from PushSubscription.getKey("p256dh").', max_length=255)),
                ('auth', models.CharField(help_text='Authentication secret (base64url) from PushSubscription.getKey("auth").', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_used_at'],
            },
        ),
    ]
