# Rebrand: PHARA -> Faralokun Vital Herbs (defaults + existing rows)
# Generated by opencode during the Faralokun rebrand.

from django.db import migrations, models


SITE_NAME = 'Faralokun Vital Herbs'


def update_branding(apps, schema_editor):
    SiteSettings = apps.get_model('api', 'SiteSettings')
    BlogPost = apps.get_model('api', 'BlogPost')

    s, _ = SiteSettings.objects.get_or_create(pk=1)
    updates = {
        'site_name': SITE_NAME,
        'about_title': f'About {SITE_NAME}',
        'footer_description': f'{SITE_NAME} is a premium herbal wellness brand, '
                              'blending traditional botanical knowledge with modern quality standards.',
        'seo_title': f'{SITE_NAME} | Premium Herbal Wellness',
        'seo_description': f'Discover premium herbal products and wellness education from '
                           f'{SITE_NAME} — traditional botanical wisdom, modern quality.',
        'whatsapp_greeting': f'Hello {SITE_NAME}! I would like to know more about your herbal wellness products.',
    }
    for field, value in updates.items():
        setattr(s, field, value)
    s.save(update_fields=list(updates))

    BlogPost.objects.filter(author__in=['PHARA Team', 'PHARA']).update(
        author='Faralokun Vital Herbs Team')


def rollback_branding(apps, schema_editor):
    SiteSettings = apps.get_model('api', 'SiteSettings')
    BlogPost = apps.get_model('api', 'BlogPost')

    s = SiteSettings.objects.filter(pk=1).first()
    if s:
        updates = {
            'site_name': 'PHARA',
            'about_title': 'About PHARA',
            'footer_description': 'PHARA is a premium herbal wellness brand, '
                                  'blending traditional botanical knowledge with modern quality standards.',
            'seo_title': 'PHARA | Premium Herbal Wellness',
            'seo_description': 'Discover premium herbal products and wellness education '
                               'from PHARA — traditional botanical wisdom, modern quality.',
            'whatsapp_greeting': 'Hello PHARA! I would like to know more about your herbal wellness products.',
        }
        for field, value in updates.items():
            setattr(s, field, value)
        s.save(update_fields=list(updates))

    BlogPost.objects.filter(author='Faralokun Vital Herbs Team').update(author='PHARA Team')


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_notification_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='author',
            field=models.CharField(default='Faralokun Vital Herbs Team', max_length=100),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='about_title',
            field=models.CharField(default='About Faralokun Vital Herbs', max_length=200),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_description',
            field=models.TextField(default='Faralokun Vital Herbs is a premium herbal wellness brand, blending traditional botanical knowledge with modern quality standards.'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='seo_description',
            field=models.TextField(default='Discover premium herbal products and wellness education from Faralokun Vital Herbs — traditional botanical wisdom, modern quality.'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='seo_title',
            field=models.CharField(default='Faralokun Vital Herbs | Premium Herbal Wellness', max_length=200),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(default='Faralokun Vital Herbs', max_length=100),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='whatsapp_greeting',
            field=models.TextField(default='Hello Faralokun Vital Herbs! I would like to know more about your herbal wellness products.'),
        ),
        migrations.RunPython(update_branding, rollback_branding),
    ]