# Generated by Django 5.2.5 on 2026-09-14 09:03

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rebrand_faralokun_vital_herbs'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='promo_video_cta_label',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='promo_video_cta_url',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='promo_video_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='promo_video_enabled',
            field=models.BooleanField(default=False, help_text='Show the promotional video section on the homepage.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='promo_video_poster',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='promo video poster'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='promo_video_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='promo_video_url',
            field=models.URLField(blank=True, help_text='YouTube / embeddable video URL'),
        ),
    ]
