# Generated by Django 5.2.5 on 2026-09-17 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_sitesettings_promo_video_cta_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='logo_contains_name',
            field=models.BooleanField(default=False, help_text='Check if your uploaded logo already includes the company name (e.g. a wordmark). The header will then show the logo alone without repeating the site name.'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='contact_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='contact_phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='whatsapp_number',
            field=models.CharField(blank=True, default='', help_text='Digits only e.g. 2348062952711', max_length=20),
        ),
    ]
