# Generated by Django 5.2.5 on 2026-09-21 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_sitesettings_logo_contains_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_video_url',
            field=models.CharField(blank=True, help_text='YouTube / embeddable video URL, or a local file path like /static/vid/0917.mp4', max_length=300),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='promo_video_url',
            field=models.CharField(blank=True, help_text='YouTube / embeddable video URL, or a local file path like /static/vid/0917.mp4', max_length=300),
        ),
    ]
