# Generated by Django 5.2.5 on 2026-09-21 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_sitesettings_hero_video_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='local_image',
            field=models.CharField(blank=True, help_text='Local file under static/, e.g. /static/img/products/ginger.jpg. Shown when no Cloudinary image is set. Survives deployment because the file ships inside your codebase.', max_length=300),
        ),
    ]
