# Generated by Django 5.2.5 on 2026-09-25 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_canonical_contact_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='local_image',
            field=models.CharField(blank=True, help_text='Absolute static path, e.g. /static/img/health/qLDdj.jpg. No spaces in filenames.', max_length=255),
        ),
        migrations.AddField(
            model_name='service',
            name='local_image',
            field=models.CharField(blank=True, help_text='Absolute static path, e.g. /static/img/health/AhcYq.jpg. No spaces in filenames.', max_length=255),
        ),
    ]
