# Generated by Django 5.2.5 on 2026-08-28 19:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner (Full Access)'), ('product_manager', 'Product Manager'), ('content_manager', 'Content Manager'), ('order_manager', 'Order Manager'), ('appointment_manager', 'Appointment Manager'), ('custom', 'Custom')], default='custom', max_length=30)),
                ('sections', models.JSONField(blank=True, default=list, help_text='Dashboard sections this user can access. Auto-filled from Role unless Role is Custom.')),
                ('is_active', models.BooleanField(default=True, help_text='Turn off to revoke dashboard access instantly without deleting the account.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff Access',
                'verbose_name_plural': 'Staff Access',
                'ordering': ['user__username'],
            },
        ),
    ]
