# Generated by Django 5.2.5 on 2026-08-29 10:46

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0002_sitesettings_booking_notification_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnatomyTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system', models.CharField(choices=[('skeletal', 'Skeletal System'), ('muscular', 'Muscular System'), ('circulatory', 'Circulatory System'), ('digestive', 'Digestive System'), ('nervous', 'Nervous System'), ('respiratory', 'Respiratory System'), ('organs', 'Organs'), ('other', 'Other')], default='skeletal', max_length=30)),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('short_description', models.CharField(max_length=300)),
                ('function', models.TextField(blank=True, help_text='What this part does.')),
                ('common_issues', models.TextField(blank=True, help_text='Common problems/conditions, one per line.')),
                ('general_info', models.TextField(blank=True, help_text='Further educational information.')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['system', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Herb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField(max_length=150)),
                ('scientific_name', models.CharField(blank=True, max_length=150)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('description', models.TextField()),
                ('traditional_uses', models.TextField(blank=True, help_text='One per line.')),
                ('compounds_info', models.TextField(blank=True, help_text='Active compounds / nutrients — educational, not a health claim.')),
                ('preparation_info', models.TextField(blank=True, help_text='How it is typically prepared or used.')),
                ('safety_info', models.TextField(blank=True)),
                ('interactions_info', models.TextField(blank=True, help_text='Possible interactions with medications, etc.')),
                ('precautions', models.TextField(blank=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_products', models.ManyToManyField(blank=True, related_name='related_herbs', to='api.product')),
            ],
            options={
                'ordering': ['sort_order', 'common_name'],
            },
        ),
        migrations.CreateModel(
            name='HealthCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('overview', models.TextField()),
                ('causes', models.TextField(blank=True, help_text='Causes / risk factors, one per line.')),
                ('symptoms', models.TextField(blank=True, help_text='One per line.')),
                ('prevention', models.TextField(blank=True, help_text='One per line.')),
                ('lifestyle_tips', models.TextField(blank=True, help_text='One per line.')),
                ('treatment_info', models.TextField(blank=True, help_text='General educational information — not a prescription or diagnosis.')),
                ('seek_care_info', models.TextField(blank=True, help_text='When to seek professional medical attention.')),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_herbs', models.ManyToManyField(blank=True, related_name='related_conditions', to='health.herb')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
