# Generated by Django 5.2.5 on 2026-09-25 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anatomytopic',
            name='local_image',
            field=models.CharField(blank=True, help_text='Absolute static path, e.g. /static/img/health/liver.jpg. No spaces in filenames.', max_length=255),
        ),
        migrations.AddField(
            model_name='healthcondition',
            name='local_image',
            field=models.CharField(blank=True, help_text='Absolute static path, e.g. /static/img/health/AhcYq.jpg. No spaces in filenames.', max_length=255),
        ),
        migrations.AddField(
            model_name='herb',
            name='local_image',
            field=models.CharField(blank=True, help_text='Absolute static path, e.g. /static/img/health/JFl7u.jpg. No spaces in filenames.', max_length=255),
        ),
    ]
